// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: storage.proto

package ipfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

type Cid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Cid) Reset() {
	*x = Cid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cid) ProtoMessage() {}

func (x *Cid) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cid.ProtoReflect.Descriptor instead.
func (*Cid) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Cid) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type APIID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	APIID string `protobuf:"bytes,1,opt,name=APIID,proto3" json:"APIID,omitempty"`
}

func (x *APIID) Reset() {
	*x = APIID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIID) ProtoMessage() {}

func (x *APIID) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIID.ProtoReflect.Descriptor instead.
func (*APIID) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *APIID) GetAPIID() string {
	if x != nil {
		return x.APIID
	}
	return ""
}

type StageCidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId *APIID `protobuf:"bytes,1,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	Cid   *Cid   `protobuf:"bytes,2,opt,name=Cid,proto3" json:"Cid,omitempty"`
}

func (x *StageCidRequest) Reset() {
	*x = StageCidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageCidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageCidRequest) ProtoMessage() {}

func (x *StageCidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageCidRequest.ProtoReflect.Descriptor instead.
func (*StageCidRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StageCidRequest) GetApiId() *APIID {
	if x != nil {
		return x.ApiId
	}
	return nil
}

func (x *StageCidRequest) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

type UnpinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId *APIID `protobuf:"bytes,1,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	Cid   *Cid   `protobuf:"bytes,2,opt,name=Cid,proto3" json:"Cid,omitempty"`
}

func (x *UnpinRequest) Reset() {
	*x = UnpinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinRequest) ProtoMessage() {}

func (x *UnpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinRequest.ProtoReflect.Descriptor instead.
func (*UnpinRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *UnpinRequest) GetApiId() *APIID {
	if x != nil {
		return x.ApiId
	}
	return nil
}

func (x *UnpinRequest) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

type PinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId *APIID `protobuf:"bytes,1,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	Cid   *Cid   `protobuf:"bytes,2,opt,name=Cid,proto3" json:"Cid,omitempty"`
}

func (x *PinRequest) Reset() {
	*x = PinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinRequest) ProtoMessage() {}

func (x *PinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinRequest.ProtoReflect.Descriptor instead.
func (*PinRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *PinRequest) GetApiId() *APIID {
	if x != nil {
		return x.ApiId
	}
	return nil
}

func (x *PinRequest) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

type PinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CumulativeSize int32 `protobuf:"varint,1,opt,name=CumulativeSize,proto3" json:"CumulativeSize,omitempty"`
}

func (x *PinResponse) Reset() {
	*x = PinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinResponse) ProtoMessage() {}

func (x *PinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinResponse.ProtoReflect.Descriptor instead.
func (*PinResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *PinResponse) GetCumulativeSize() int32 {
	if x != nil {
		return x.CumulativeSize
	}
	return 0
}

type ReplaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId  *APIID `protobuf:"bytes,1,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	Source *Cid   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Dest   *Cid   `protobuf:"bytes,3,opt,name=Dest,proto3" json:"Dest,omitempty"`
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRequest.ProtoReflect.Descriptor instead.
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ReplaceRequest) GetApiId() *APIID {
	if x != nil {
		return x.ApiId
	}
	return nil
}

func (x *ReplaceRequest) GetSource() *Cid {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ReplaceRequest) GetDest() *Cid {
	if x != nil {
		return x.Dest
	}
	return nil
}

type ReplaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int32 `protobuf:"varint,1,opt,name=Res,proto3" json:"Res,omitempty"`
}

func (x *ReplaceResponse) Reset() {
	*x = ReplaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResponse) ProtoMessage() {}

func (x *ReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceResponse.ProtoReflect.Descriptor instead.
func (*ReplaceResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ReplaceResponse) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

type IsPinnedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId *APIID `protobuf:"bytes,1,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	Cid   *Cid   `protobuf:"bytes,2,opt,name=Cid,proto3" json:"Cid,omitempty"`
}

func (x *IsPinnedRequest) Reset() {
	*x = IsPinnedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPinnedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPinnedRequest) ProtoMessage() {}

func (x *IsPinnedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPinnedRequest.ProtoReflect.Descriptor instead.
func (*IsPinnedRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *IsPinnedRequest) GetApiId() *APIID {
	if x != nil {
		return x.ApiId
	}
	return nil
}

func (x *IsPinnedRequest) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

type IsPinnedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pinned bool `protobuf:"varint,1,opt,name=Pinned,proto3" json:"Pinned,omitempty"`
}

func (x *IsPinnedResponse) Reset() {
	*x = IsPinnedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPinnedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPinnedResponse) ProtoMessage() {}

func (x *IsPinnedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPinnedResponse.ProtoReflect.Descriptor instead.
func (*IsPinnedResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *IsPinnedResponse) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type GCStagedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid  []*Cid `protobuf:"bytes,1,rep,name=Cid,proto3" json:"Cid,omitempty"`
	Time string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GCStagedRequest) Reset() {
	*x = GCStagedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCStagedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCStagedRequest) ProtoMessage() {}

func (x *GCStagedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCStagedRequest.ProtoReflect.Descriptor instead.
func (*GCStagedRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *GCStagedRequest) GetCid() []*Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *GCStagedRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GCStagedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid []*Cid `protobuf:"bytes,1,rep,name=Cid,proto3" json:"Cid,omitempty"`
}

func (x *GCStagedResponse) Reset() {
	*x = GCStagedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCStagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCStagedResponse) ProtoMessage() {}

func (x *GCStagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCStagedResponse.ProtoReflect.Descriptor instead.
func (*GCStagedResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GCStagedResponse) GetCid() []*Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

var file_storage_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x69, 0x70, 0x66, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17,
	0x0a, 0x03, 0x43, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x1d, 0x0a, 0x05, 0x41, 0x50, 0x49, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x41, 0x50, 0x49, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x41, 0x50, 0x49, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x41, 0x70, 0x69,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e,
	0x41, 0x50, 0x49, 0x49, 0x44, 0x52, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x03,
	0x43, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x0c, 0x55, 0x6e, 0x70,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x41, 0x70, 0x69,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e,
	0x41, 0x50, 0x49, 0x49, 0x44, 0x52, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x03,
	0x43, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x0a, 0x50, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x41, 0x50,
	0x49, 0x49, 0x44, 0x52, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x43, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x43,
	0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x75,
	0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x49, 0x44, 0x52, 0x05, 0x41, 0x70,
	0x69, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x52, 0x06,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x52,
	0x04, 0x44, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x49, 0x73,
	0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69,
	0x70, 0x66, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x49, 0x44, 0x52, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x22, 0x2a, 0x0a,
	0x10, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x42, 0x0a, 0x0f, 0x47, 0x43, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x03,
	0x43, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a,
	0x10, 0x47, 0x43, 0x53, 0x74, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x43, 0x69, 0x64, 0x32, 0xb4,
	0x03, 0x0a, 0x04, 0x49, 0x50, 0x46, 0x53, 0x12, 0x21, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x49, 0x44, 0x1a, 0x09, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x43, 0x69, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x43, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x05,
	0x55, 0x6e, 0x70, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x55, 0x6e, 0x70,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x03, 0x50, 0x69, 0x6e, 0x12,
	0x10, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x1f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x09, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x64, 0x1a, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x08, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x15, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x2e, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x49, 0x73, 0x50, 0x69,
	0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x08, 0x47, 0x43, 0x53, 0x74, 0x61, 0x67, 0x65, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x70, 0x66,
	0x73, 0x2e, 0x47, 0x43, 0x53, 0x74, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x47, 0x43, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x0a, 0x50,
	0x69, 0x6e, 0x6e, 0x65, 0x64, 0x43, 0x69, 0x64, 0x73, 0x12, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x69, 0x70, 0x66, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData = file_storage_proto_rawDesc
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_proto_rawDescData)
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_storage_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: ipfs.Empty
	(*Cid)(nil),              // 1: ipfs.Cid
	(*APIID)(nil),            // 2: ipfs.APIID
	(*StageCidRequest)(nil),  // 3: ipfs.StageCidRequest
	(*UnpinRequest)(nil),     // 4: ipfs.UnpinRequest
	(*PinRequest)(nil),       // 5: ipfs.PinRequest
	(*PinResponse)(nil),      // 6: ipfs.PinResponse
	(*ReplaceRequest)(nil),   // 7: ipfs.ReplaceRequest
	(*ReplaceResponse)(nil),  // 8: ipfs.ReplaceResponse
	(*IsPinnedRequest)(nil),  // 9: ipfs.IsPinnedRequest
	(*IsPinnedResponse)(nil), // 10: ipfs.IsPinnedResponse
	(*GCStagedRequest)(nil),  // 11: ipfs.GCStagedRequest
	(*GCStagedResponse)(nil), // 12: ipfs.GCStagedResponse
}
var file_storage_proto_depIdxs = []int32{
	2,  // 0: ipfs.StageCidRequest.ApiId:type_name -> ipfs.APIID
	1,  // 1: ipfs.StageCidRequest.Cid:type_name -> ipfs.Cid
	2,  // 2: ipfs.UnpinRequest.ApiId:type_name -> ipfs.APIID
	1,  // 3: ipfs.UnpinRequest.Cid:type_name -> ipfs.Cid
	2,  // 4: ipfs.PinRequest.ApiId:type_name -> ipfs.APIID
	1,  // 5: ipfs.PinRequest.Cid:type_name -> ipfs.Cid
	2,  // 6: ipfs.ReplaceRequest.ApiId:type_name -> ipfs.APIID
	1,  // 7: ipfs.ReplaceRequest.Source:type_name -> ipfs.Cid
	1,  // 8: ipfs.ReplaceRequest.Dest:type_name -> ipfs.Cid
	2,  // 9: ipfs.IsPinnedRequest.ApiId:type_name -> ipfs.APIID
	1,  // 10: ipfs.IsPinnedRequest.Cid:type_name -> ipfs.Cid
	1,  // 11: ipfs.GCStagedRequest.Cid:type_name -> ipfs.Cid
	1,  // 12: ipfs.GCStagedResponse.Cid:type_name -> ipfs.Cid
	2,  // 13: ipfs.IPFS.Stage:input_type -> ipfs.APIID
	3,  // 14: ipfs.IPFS.StageCid:input_type -> ipfs.StageCidRequest
	4,  // 15: ipfs.IPFS.Unpin:input_type -> ipfs.UnpinRequest
	5,  // 16: ipfs.IPFS.Pin:input_type -> ipfs.PinRequest
	1,  // 17: ipfs.IPFS.Get:input_type -> ipfs.Cid
	7,  // 18: ipfs.IPFS.Replace:input_type -> ipfs.ReplaceRequest
	9,  // 19: ipfs.IPFS.IsPinned:input_type -> ipfs.IsPinnedRequest
	11, // 20: ipfs.IPFS.GCStaged:input_type -> ipfs.GCStagedRequest
	0,  // 21: ipfs.IPFS.PinnedCids:input_type -> ipfs.Empty
	1,  // 22: ipfs.IPFS.Stage:output_type -> ipfs.Cid
	0,  // 23: ipfs.IPFS.StageCid:output_type -> ipfs.Empty
	0,  // 24: ipfs.IPFS.Unpin:output_type -> ipfs.Empty
	6,  // 25: ipfs.IPFS.Pin:output_type -> ipfs.PinResponse
	0,  // 26: ipfs.IPFS.Get:output_type -> ipfs.Empty
	8,  // 27: ipfs.IPFS.Replace:output_type -> ipfs.ReplaceResponse
	10, // 28: ipfs.IPFS.IsPinned:output_type -> ipfs.IsPinnedResponse
	12, // 29: ipfs.IPFS.GCStaged:output_type -> ipfs.GCStagedResponse
	0,  // 30: ipfs.IPFS.PinnedCids:output_type -> ipfs.Empty
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageCidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPinnedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPinnedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCStagedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCStagedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_rawDesc = nil
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
